### ISSUE TITLE
Catching a connect error

### ISSUE THREAD

**Issue by uSlackr** [jhoneill/GetSQL#3]
I need to be able to catch connection failures.  When connections fail, get-sql generates a Warning so this code doesn't work.  I tried adding `-Erroraction stop` as well.
```
try {
   get-sql -MsSQLserver -connection $Conn -Session TT 
} catch {
   echo "error connection to $Conn"
}
```

**Comment by jhoneill** [comment]
Does running with `-warningaction stop` do what you need ?

**Comment by uSlackr** [comment]
It's that a thing??  I'll try it.


\\Greg
________________________________

**Comment by uSlackr** [comment]
I can confirm that worked.  Learned something new.  Thanks

**Comment by jhoneill** [comment]
Thanks for confirming.
